version: '3.8'

services:
  app:
    image: fahadkabir123/flask-jwt-auth:latest
    ports:
      - '5001:5001' # Map host port 5001 to container port 5001
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - auth-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5002:5432' # Expose PostgreSQL port to host
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - auth-network

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env.pgAdmin
    ports:
      - '5050:80' # Expose pgAdmin web interface on port 5050
    depends_on:
      - db
    networks:
      - auth-network

volumes:
  postgres_data:

networks:
  auth-network:
    driver: bridge
